export default [
    {
        _id: 'm101',
        title: 'Inception',
        director: 'Christopher Nolan',
        posterUrl: 'https://image.tmdb.org/t/p/w500/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg',
        runningTime: 148,
        releaseYear: 2010,
        actors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
        genre: 'Science Fiction',
    },
    {
        _id: 'm102',
        title: 'The Grand Budapest Hotel',
        director: 'Wes Anderson',
        posterUrl: 'https://image.tmdb.org/t/p/w500/nX5XotM9yprCKarRH4fzOq1VM1J.jpg',
        runningTime: 99,
        releaseYear: 2014,
        actors: ['Ralph Fiennes', 'Tony Revolori', 'Saoirse Ronan'],
        genre: 'Comedy',
    },
    {
        _id: 'm103',
        title: 'Parasite',
        director: 'Bong Joon-ho',
        posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
        runningTime: 132,
        releaseYear: 2019,
        actors: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
        genre: 'Thriller',
    },
    {
        _id: 'm104',
        title: 'Spirited Away',
        director: 'Hayao Miyazaki',
        posterUrl: 'https://image.tmdb.org/t/p/w500/dL11DBPcRhWWnJcFXl9A07MrqTI.jpg',
        runningTime: 125,
        releaseYear: 2001,
        actors: ['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki'],
        genre: 'Animation',
    },
    {
        _id: 'm105',
        title: 'The Social Network',
        director: 'David Fincher',
        posterUrl: 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
        runningTime: 120,
        releaseYear: 2010,
        actors: ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake'],
        genre: 'Drama',
    },
]
